const express = require('express');
const authController = require('../../Controllers/user/authController');
const { model } = require('mongoose');
const router = express.Router();
router.post('/register', authController.register);
router.post('/login', authController.login);
router.get('/logout', authController.logout);
router.get('/me', authController.getMe);
router.put('/updatepassword', authController.updatePassword);
router.put('/updateuser', authController.updateUser);
router.delete('/deleteuser', authController.deleteUser);
model.exports = router;